GET http://localhost:3000/

###
GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/2

###
DELETE  http://localhost:3000/ads/9

###
POST http://localhost:3000/ads
Content-Type: application/json

{
  "title": "Ad 5",
  "description": "Description 5", 
  "owner": "Owner 5",
  "price": 90,
  "picture": "Image 5",
  "location": "Location 5"
}
###