GET http://localhost:3000/

###
GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/2

###
DELETE  http://localhost:3000/ads/415

###
POST http://localhost:3000/ads
Content-Type: application/json

{
  "title": "Ad 10",
  "description": "Description 10", 
  "owner": "Owner 10",
  "price": 90,
  "picture": "Image 10",
  "location": "Location 10"
}
###