                                                      // AD TESTS
GET http://localhost:3000/api/ads

###
GET http://localhost:3000/api/ads/2

###
DELETE  http://localhost:3000/api/ads/1

###
POST http://localhost:3000/api/ads
Content-Type: application/json

{
  "title": "ANONCE 10",
  "description": "DESCROldhfgdugfidofhsio 10", 
  "owner": "Owner 10",
  "price": 90,
  "picture": "Image 10",
  "location": "Location 10",
  "category_id": 1 ,
  "tags_id": [1, 2]
}
###

PUT http://localhost:3000/api/ad/2
Content-Type: application/json

{
  "title": "ANONCE 1",
  "description": "DESCROldhfgdugfidofhsio 1", 
  "owner": "Owner 1",
  "price": 90,
  "picture": "Image 1",
  "location": "Location 1",
  "category_id": 2,
  "tags_id": 1 2 
}

                                                     // CATEGORY TESTS

###

POST http://localhost:3000/api/category
Content-Type: application/json

{
  "name": "Category 2"
}

###

GET http://localhost:3000/api/category/1


                                                     // TAGS TESTS

###
POST http://localhost:3000/api/tags
Content-Type: application/json

{
  "tag": "Tag 4"
}

###
GET http://localhost:3000/api/tags


###
GET http://localhost:3000/api/tags/1

###
DELETE http://localhost:3000/api/tags/4