
GET http://localhost:3000/ads

###
GET http://localhost:3000/ads/2

###
DELETE  http://localhost:3000/ads/1

###
POST http://localhost:3000/ads
Content-Type: application/json

{
  "title": "ANONCE 10",
  "description": "DESCROldhfgdugfidofhsio 10", 
  "owner": "Owner 10",
  "price": 90,
  "picture": "Image 10",
  "location": "Location 10"
}
###

PUT http://localhost:3000/ad/4
Content-Type: application/json

{
  "title": "ANONCE 1",
  "description": "DESCROldhfgdugfidofhsio 1", 
  "owner": "Owner 1",
  "price": 90,
  "picture": "Image 1",
  "location": "Location 1"
}